### PR TITLE
feat: added mapping for cors policy

### PR DESCRIPTION
**Pull request by maxt0214**

### CODE REVIEW

**Comment by maxt0214** [comment]
resolves #86

**Comment by nmcharlton** [comment]
@Kpoke @dadiorchen Can we get this PR merged?

**Comment by Kpoke** [comment]
@maxt0214 , @nmcharlton do we need to run this in production as well?

**Comment by Kpoke** [comment]
Okay, I guess we could leave it as is then and see how it goes

**Pull request merged**
